---
dependencies:
  - role: repo_gentoo

galaxy_info:
  role_name: portage_package
  description: |
    This role installs some portage packages.
  author: Alexander Puck Neuwirth
  platforms:
    - name: Gentoo
      versions:
        - all
  license: GPLv3
  min_ansible_version: "2.0"
