---
- name: Demo playbook for rolling-ansible-container
  hosts: all
  become: true

  tasks:
  - name: Install git and curl
    ansible.builtin.package:
      name:
        - git
      state: present
